project:
  type: website

website:
  title: "mq-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    # theme: cosmo
    theme: simplex
    css: styles.css



